PROMPT_TEMPLATE_INIT=initial.ftl
PROMPT_TEMPLATE_INIT_SYSTEM=initial_system.ftl
PROMPT_TEMPLATE_EXTRA=extra.ftl
PROMPT_TEMPLATE_REPAIR=repair.ftl
PROMPT_TEMPLATE_TESTPILOT_INIT=initial_testpilot.ftl
PROMPT_TEMPLATE_SYMPROMPT_INIT_SYSTEM=initial_symprompt.ftl
PROMPT_TEMPLATE_SYMPROMPT_INIT=initial_symprompt_system.ftl
PROMPT_TEMPLATE_TELPA_INIT=initial_telpa.ftl
PROMPT_TEMPLATE_COVERUP_REPAIR=coverage.ftl
PROMPT_TEMPLATE_HITS_GEN_SLICE = hits_gen_slice.ftl
PROMPT_TEMPLATE_HITS_GEN = hits_gen.ftl
PROMPT_TEMPLATE_HITS_SYS_GEN = hits_system_gen.ftl
PROMPT_TEMPLATE_HITS_REPAIR = hits_repair.ftl
PROMPT_TEMPLATE_HITS_SYS_REPAIR = hits_system_repair.ftl
PROMPT_TEMPLATE_CHATTESTER_INIT = chattester_initial.ftl
PROMPT_TEMPLATE_CHATTESTER_EXTRA = chattester_extra.ftl
PROMPT_TEMPLATE_CHATTESTER_REPAIR = chattester_repair.ftl
PROMPT_TEMPLATE_TESTSPARK_INIT = testspark_initial.ftl
PROMPT_TEMPLATE_TESTSPARK_REPAIR = testspark_repair.ftl
PROMPT_TEMPLATE_MUTAPINIT=initial_mutation.ftl

PROMPT_TEMPLATE_SCOUT_INITIAL_NO_DEPS=scout_initial_no_deps.ftl
PROMPT_TEMPLATE_SCOUT_INITIAL_WITH_DEPS=scout_initial_with_deps.ftl
PROMPT_TEMPLATE_SCOUT_INITIAL_CONSTR_NO_DEPS=scout_initial_constr_no_deps.ftl
PROMPT_TEMPLATE_SCOUT_INITIAL_CONSTR_WITH_DEPS=scout_initial_constr_with_deps.ftl
PROMPT_TEMPLATE_SCOUT_CACHE_NO_DEPS=scout_cache_no_deps.ftl
PROMPT_TEMPLATE_SCOUT_CACHE_WITH_DEPS=scout_cache_with_deps.ftl
PROMPT_TEMPLATE_SCOUT_GUIDE_COVERAGE=scout_guide_coverage.ftl
PROMPT_TEMPLATE_SCOUT_GUIDE_COVERAGE_NO_BRANCH=scout_guide_coverage_no_branch.ftl
PROMPT_TEMPLATE_SCOUT_GUIDE_COVERAGE_CALLERS=scout_guide_coverage_callers.ftl
PROMPT_TEMPLATE_SCOUT_ERROR=scout_error.ftl
PROMPT_TEMPLATE_SCOUT_ERROR_CONSTR=scout_error_constr.ftl
PROMPT_TEMPLATE_SCOUT_FAIL=scout_fail.ftl
PROMPT_TEMPLATE_SCOUT_EXPORT_PROJECT=scout_export_project.ftl
PROMPT_TEMPLATE_SCOUT_EXPORT_PROJECT_SYSTEM=scout_export_project_system.ftl
PROMPT_TEMPLATE_SCOUT_EXPORT_CLASS=scout_export_class.ftl
PROMPT_TEMPLATE_SCOUT_EXPORT_CLASS_SYSTEM=scout_export_class_system.ftl
PROMPT_TEMPLATE_SCOUT_EXPORT_CLASS_ASPECT=scout_export_class_aspect.ftl
PROMPT_TEMPLATE_SCOUT_EXPORT_METHOD=scout_export_method.ftl
PROMPT_TEMPLATE_SCOUT_EXPORT_METHOD_SYSTEM=scout_export_method_system.ftl
PROMPT_TEMPLATE_SCOUT_EXPORT_METHOD_SCENARIO=scout_export_method_scenario.ftl